using System.Text;

namespace Devenv;

public sealed record FrontendRenderInput(
    Manifest Manifest,
    EnvironmentSpec Environment,
    IReadOnlyDictionary<string, string> Secrets,
    string GatewayOrigin,
    string FrontendOrigin);

/// <summary>Renders apps/dss/.env: base path = local libertine, Okta values per environment, secrets from secrets.json.</summary>
public static class FrontendEnvRenderer
{
    public static string Render(FrontendRenderInput input)
    {
        var fe = input.Manifest.Frontend;
        var env = input.Environment;

        var missing = fe.Secrets.Required
            .Where(k => !input.Secrets.TryGetValue(k, out var v) || string.IsNullOrWhiteSpace(v))
            .ToList();
        if (missing.Count > 0)
        {
            throw new DevenvException($"frontend secrets missing or blank in secrets.json: {string.Join(", ", missing)} (run `devenv setup`, or see secrets.example.json for the 1Password location)");
        }

        var lines = new List<(string Key, string Value)>
        {
            ("NEXT_PUBLIC_VERA_BASE_PATH", input.GatewayOrigin),
            ("NEXTAUTH_URL", input.FrontendOrigin),
            ("OKTA_ISSUER", env.Okta.Authority),
            ("OKTA_CLIENT_ID", env.Okta.FrontendClientId),
        };
        foreach (var (k, v) in env.Frontend.OrderBy(kv => kv.Key, StringComparer.Ordinal))
        {
            lines.Add((k, v));
        }
        foreach (var k in fe.Secrets.Required)
        {
            lines.Add((k, input.Secrets[k]));
        }
        foreach (var k in fe.Secrets.Optional)
        {
            lines.Add((k, input.Secrets.TryGetValue(k, out var v) ? v : ""));
        }

        var sb = new StringBuilder();
        sb.AppendLine($"# Generated by devenv for {env.Name} on {DateTimeOffset.Now:yyyy-MM-dd HH:mm}. Do not edit: change devenv/secrets.json or");
        sb.AppendLine($"# environments/{env.Name}.json and run `devenv render`. Gitignored. Next.js reads this file only at startup.");
        foreach (var (k, v) in lines)
        {
            sb.Append(k).Append('=').AppendLine(Quote(v));
        }
        return sb.ToString();
    }

    private static string Quote(string value) =>
        value.All(c => !char.IsWhiteSpace(c) && c != '#' && c != '"' && c != '\'')
            ? value
            : "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
