using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

namespace Devenv;

public sealed record LibertineRenderInput(
    string TemplateJson,
    Manifest Manifest,
    EnvironmentSpec Environment,
    IReadOnlyList<ServiceSpec> LocalServices,
    string OktaInternalSecret,
    string DeveloperName,
    string OtlpEndpoint,
    string FrontendOrigin);

/// <summary>
/// Renders libertine's appsettings.Development.json from the committed envsubst template.
/// The template's ServiceSettings entries and YARP clusters are the source of truth; this only decides
/// which host each one points at (remote internal ingress, remote public host, or localhost for a
/// service running on this machine) and adds the edge routes that make libertine the single local origin.
/// </summary>
public static partial class LibertineConfigRenderer
{
    [GeneratedRegex(@"\$[A-Za-z_][A-Za-z0-9_]*")]
    private static partial Regex Placeholder();

    public static string Render(LibertineRenderInput input)
    {
        var template = JsonNode.Parse(input.TemplateJson, documentOptions: new JsonDocumentOptions { CommentHandling = JsonCommentHandling.Skip, AllowTrailingCommas = true })?.AsObject()
            ?? throw new DevenvException("libertine template is not a JSON object");
        var m = input.Manifest;
        var env = input.Environment;
        var gw = m.Gateway;

        var output = new JsonObject
        {
            ["_generated"] = $"Generated by devenv for {env.Name} on {DateTimeOffset.Now:yyyy-MM-dd HH:mm}. Do not edit: change devenv/manifest.json, environments/{env.Name}.json or devenv.local.json and run `devenv render`. Gitignored.",
        };

        // --- ServiceSettings.Services -------------------------------------------------------------
        var services = new JsonArray();
        var templateServices = template["ServiceSettings"]?["Services"]?.AsArray()
            ?? throw new DevenvException("libertine template has no ServiceSettings.Services");
        foreach (var entry in templateServices)
        {
            var name = entry?["Name"]?.GetValue<string>() ?? throw new DevenvException("ServiceSettings entry without Name");
            var local = input.LocalServices.FirstOrDefault(s => s.ServiceSettingsNames.Contains(name, StringComparer.OrdinalIgnoreCase));
            gw.ServiceSettings.TryGetValue(name, out var over);
            string host = local is not null
                ? LocalHost(local.Port)
                : (over?.Ingress == "public" ? env.PublicBaseUrl : env.InternalBaseUrl);

            string Rewrite(string committed) => Join(host, over?.Path ?? ExtractPath(committed));

            services.Add(new JsonObject
            {
                ["Name"] = name,
                ["Url"] = Rewrite(entry["Url"]?.GetValue<string>() ?? ""),
                ["Domain"] = Rewrite(entry["Domain"]?.GetValue<string>() ?? ""),
            });
        }
        output["ServiceSettings"] = new JsonObject { ["Services"] = services };

        // --- Logging, auth, telemetry ---------------------------------------------------------------
        output["Logging"] = new JsonObject
        {
            ["LogLevel"] = new JsonObject
            {
                ["Default"] = "Information",
                ["Microsoft.AspNetCore"] = "Warning",
                ["Yarp"] = "Information",
            },
            ["Console"] = new JsonObject { ["IncludeScopes"] = "false" },
        };
        output["AllowedHosts"] = "*";
        output["SecuritySettings"] = new JsonObject
        {
            ["Authority"] = env.IdentityAuthority,
            ["Audience"] = "api",
            ["Audiences"] = new JsonArray("api", "internalapi"),
            ["OktaAuthority"] = env.Okta.Authority,
            ["OktaAudience"] = env.Okta.Audience,
            ["OktaAudiences"] = env.Okta.Audiences,
        };
        output["InternalServiceSettings"] = new JsonObject
        {
            ["disco"] = env.Okta.Authority,
            ["clientId"] = env.Okta.InternalClientId,
            ["scope"] = "internalapi",
            ["secret"] = input.OktaInternalSecret,
        };

        // --- ReverseProxy.Clusters: every committed cluster, re-pointed -----------------------------
        var templateClusters = template["ReverseProxy"]?["Clusters"]?.AsObject()
            ?? throw new DevenvException("libertine template has no ReverseProxy.Clusters");
        var clusters = new JsonObject();
        foreach (var (clusterId, clusterNode) in templateClusters)
        {
            var destinations = clusterNode?["Destinations"]?.AsObject()
                ?? throw new DevenvException($"cluster '{clusterId}' has no Destinations");
            var (destKey, destNode) = destinations.First();
            var committed = destNode?["Address"]?.GetValue<string>() ?? "";
            var local = input.LocalServices.FirstOrDefault(s => s.ClusterIds.Contains(clusterId, StringComparer.Ordinal));
            string host = local is not null
                ? LocalHost(local.Port)
                : (gw.PublicClusters.Contains(clusterId, StringComparer.Ordinal) ? env.PublicBaseUrl : env.InternalBaseUrl);
            clusters[clusterId] = new JsonObject
            {
                ["Destinations"] = new JsonObject
                {
                    [destKey] = new JsonObject { ["Address"] = Join(host, ExtractPath(committed)) },
                },
            };
        }

        // --- Edge: what the frontend calls outside /libertine ---------------------------------------
        var publicClusterId = $"{env.Name}-public";
        clusters[publicClusterId] = Cluster(Join(env.PublicBaseUrl, ""));

        var routes = new JsonObject();
        var edgeByPrefix = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var prefix in gw.EdgeRoutes)
        {
            edgeByPrefix[prefix.Trim('/')] = publicClusterId;
        }
        foreach (var local in input.LocalServices.Where(s => s.PublicPrefix is not null))
        {
            var prefix = local.PublicPrefix!.Trim('/');
            var localClusterId = $"local-{local.Name}";
            clusters[localClusterId] = Cluster(Join(LocalHost(local.Port), ""));
            edgeByPrefix[prefix] = localClusterId; // overrides a general prefix, or adds a more specific one
        }
        foreach (var (prefix, clusterId) in edgeByPrefix)
        {
            routes[$"edge-{Slug(prefix)}"] = new JsonObject
            {
                ["ClusterId"] = clusterId,
                ["Match"] = new JsonObject { ["Path"] = $"{prefix}/{{**catch-all}}" },
            };
        }

        output["ReverseProxy"] = new JsonObject { ["Clusters"] = clusters, ["Routes"] = routes };

        output["serviceName"] = new JsonObject { ["serviceEnv"] = $"Local-DEV-{input.DeveloperName}" };
        output["OpenTelemetry"] = new JsonObject { ["OTLP"] = new JsonObject { ["Endpoint"] = input.OtlpEndpoint } };
        output["LocalDev"] = new JsonObject
        {
            ["CorsOrigins"] = new JsonArray(input.FrontendOrigin),
            ["MaxRequestBodySize"] = gw.MaxRequestBodySize,
        };

        var json = output.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
        var leftover = Placeholder().Match(json);
        if (leftover.Success)
        {
            throw new DevenvException($"rendered libertine config still contains placeholder {leftover.Value}; the template has a shape this renderer does not understand");
        }
        return json;
    }

    private static JsonObject Cluster(string address) => new()
    {
        ["Destinations"] = new JsonObject { ["Route"] = new JsonObject { ["Address"] = address } },
    };

    private static string LocalHost(int port) => $"http://localhost:{port}";

    /// <summary>"http://$Svc.svc.cluster.local/Vera/UserService/" → "Vera/UserService/"; a bare placeholder → "".</summary>
    public static string ExtractPath(string committedAddress)
    {
        var s = committedAddress.Trim();
        foreach (var scheme in new[] { "https://", "http://" })
        {
            if (s.StartsWith(scheme, StringComparison.OrdinalIgnoreCase))
            {
                s = s[scheme.Length..];
                break;
            }
        }
        var slash = s.IndexOf('/');
        return slash < 0 ? "" : s[(slash + 1)..];
    }

    private static string Join(string host, string path) => host.TrimEnd('/') + "/" + path.TrimStart('/');

    private static string Slug(string prefix)
    {
        var chars = prefix.ToLowerInvariant().TrimStart('.').Select(c => char.IsLetterOrDigit(c) ? c : '-').ToArray();
        return new string(chars).Trim('-');
    }
}
