namespace Devenv;

/// <summary>Turns a workspace into the generated files and knows where they go.</summary>
public static class Renderers
{
    public sealed record Rendered(string Name, string Path, string Content, IReadOnlyList<string> Warnings);

    public static Rendered Libertine(Workspace ws)
    {
        var gw = ws.Manifest.Gateway;
        var repo = ws.RepoPath(gw.Repo);
        var templatePath = Path.Combine(repo, gw.ConfigTemplate);
        if (!File.Exists(templatePath))
        {
            throw new DevenvException($"libertine template not found: {templatePath} (is {gw.Repo} cloned next to mavera-compose, or set reposRoot in devenv.local.json?)");
        }
        var json = LibertineConfigRenderer.Render(new LibertineRenderInput(
            File.ReadAllText(templatePath),
            ws.Manifest,
            ws.Environment,
            ws.LocalServices,
            ws.RequireSecret(gw.OktaInternalSecretKey),
            ws.DeveloperName,
            ws.Local.OtlpEndpoint,
            ws.FrontendOrigin));
        return new Rendered("libertine", Path.Combine(repo, gw.ConfigOutput), json, Array.Empty<string>());
    }

    public static Rendered Frontend(Workspace ws)
    {
        var fe = ws.Manifest.Frontend;
        if (!ws.HasSecretsFile)
        {
            throw new DevenvException($"secrets.json not found at {ws.SecretsFile}; run `devenv setup` (see README)");
        }
        var content = FrontendEnvRenderer.Render(new FrontendRenderInput(
            ws.Manifest, ws.Environment, ws.Secrets, ws.GatewayOrigin, ws.FrontendOrigin));
        return new Rendered("frontend", Path.Combine(ws.RepoPath(fe.Repo), fe.WorkingDir, fe.EnvFile), content, Array.Empty<string>());
    }

    /// <summary>A backend service running on this machine: its committed template, substituted and re-pointed.</summary>
    public static Rendered Service(Workspace ws, ServiceSpec service)
    {
        if (service.Project is null)
        {
            throw new DevenvException($"{service.Name}: manifest has no project path yet; set services[].project to the web project's .csproj (relative to the repo) to run it locally");
        }
        var repo = ws.RepoPath(service.Repo);
        var projectDir = Path.Combine(repo, service.ProjectDir);
        var templatePath = Path.Combine(projectDir, service.ConfigTemplate);
        if (!File.Exists(templatePath))
        {
            throw new DevenvException($"{service.Name}: template not found: {templatePath} (is {service.Repo} cloned next to mavera-compose?)");
        }
        var template = File.ReadAllText(templatePath);

        var used = PlaceholderTable.TokensIn(template);
        var composeDefaults = ComposeDefaults(ws);
        var computed = new Dictionary<string, string>
        {
            ["ServiceSettings_ENV"] = $"Local-DEV-{ws.DeveloperName}",
            ["Tracing_Connection_String"] = ws.Local.OtlpEndpoint,
        };
        var resolution = PlaceholderTable.Resolve(composeDefaults, ws.Environment, ws.Manifest.Placeholders, service.Placeholders, computed, ws.Secrets, used);
        if (resolution.MissingRequiredSecrets.Count > 0)
        {
            throw new DevenvException($"{service.Name}: secrets missing or blank in secrets.json: {string.Join(", ", resolution.MissingRequiredSecrets)} (see secrets.example.json)");
        }

        var note = $"Generated by devenv for {ws.Environment.Name} on {DateTimeOffset.Now:yyyy-MM-dd HH:mm} from {service.ConfigTemplate}. Do not edit: change devenv/manifest.json, environments/{ws.Environment.Name}.json or secrets.json and run `devenv render --local {service.Name}`. Gitignored.";
        var result = ServiceConfigRenderer.Render(new ServiceRenderInput(
            service, template, resolution.Values, ws.Manifest, ws.Environment, ws.LocalServices, note, ws.SqlHost));

        var warnings = new List<string>(result.Warnings);
        if (resolution.Blank.Count > 0)
        {
            warnings.Add($"blank placeholders: {string.Join(", ", resolution.Blank)} (fine unless the service needs them)");
        }
        return new Rendered(service.Name, Path.Combine(projectDir, service.ConfigOutput), result.Json, warnings);
    }

    public static IReadOnlyDictionary<string, string> ComposeDefaults(Workspace ws)
    {
        var source = ws.Manifest.Placeholders.Source;
        if (string.IsNullOrWhiteSpace(source))
        {
            return new Dictionary<string, string>();
        }
        var path = Path.GetFullPath(Path.Combine(ws.Root, source));
        if (!File.Exists(path))
        {
            throw new DevenvException($"placeholder source not found: {path} (manifest placeholders.source)");
        }
        var defaults = PlaceholderTable.ParseComposeDefaults(File.ReadAllText(path));
        if (defaults.Count == 0)
        {
            throw new DevenvException($"no x-placeholders block found in {path}");
        }
        return defaults;
    }

    public static IReadOnlyList<Rendered> All(Workspace ws)
    {
        var list = new List<Rendered> { Libertine(ws), Frontend(ws) };
        list.AddRange(ws.LocalServices.Select(s => Service(ws, s)));
        return list;
    }

    /// <summary>Writes the file; a pre-existing hand-written file (one without the _generated marker) is copied to .state/backups first.</summary>
    public static string? Write(Rendered r, Workspace ws)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(r.Path)!);
        string? backup = null;
        if (File.Exists(r.Path))
        {
            var existing = File.ReadAllText(r.Path);
            var generated = existing.Contains("_generated", StringComparison.Ordinal) || existing.StartsWith("# Generated by devenv", StringComparison.Ordinal);
            if (!generated && existing != r.Content)
            {
                var dir = Path.Combine(ws.StateDir, "backups", r.Name);
                Directory.CreateDirectory(dir);
                backup = Path.Combine(dir, $"{DateTime.Now:yyyyMMdd-HHmmss}-{Path.GetFileName(r.Path)}");
                File.Copy(r.Path, backup, overwrite: true);
            }
        }
        File.WriteAllText(r.Path, r.Content);
        return backup;
    }
}
